version: "2.4"

services:

  rickroll:
    image: modem7/docker-rickroll
    container_name: Rickroll
    ports:
      - 8080:8080
    environment:
      - TITLE="Rickroll" # Changes the title of the webpage


