services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=db
      - DB_NAME=natixisdb
      - DB_USER=natixisuser
      - DB_PASSWORD=natixispass
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_USER: natixisuser
      MYSQL_PASSWORD: natixispass
      MYSQL_DATABASE: natixisdb
      MYSQL_ROOT_PASSWORD: natixispass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: