# Imagem base
FROM node:20-alpine

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os ficheiros necessários
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar código
COPY . .

# Build do código
RUN npm run build

# Expor a porta padrão
EXPOSE 3000

# Comando padrão para iniciar a aplicação
CMD ["node", "build/server.js"]