---
name: Publish Sleep App

on:
  push:
    branches: [ "master" ]
    paths:
      - 'examples/chapter-2/sleep-app/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/sleep-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Extract metadata for Docker
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          tags: |
#            type=sha
#            type=ref,event=branch
#            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: examples/chapter-2/sleep-app
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
